config/routes.rb
Rails.application.routes.draw do
  resources :getaway_searches do
  member do
    get "vote"
    get "render_trip_options_list"
  end
end

  devise_for :users, controllers: {registrations: "users/registrations", sessions: "users/sessions", passwords: "users/passwords"}, skip: [:sessions, :registrations]

  root 'getaway_searches#index'
  mount Resque::Server, :at => "/resque"

  
  devise_scope :user do
    get    "login"   => "users/sessions#new",         as: :new_user_session
    post   "login"   => "users/sessions#create",      as: :user_session
    delete "signout" => "users/sessions#destroy",     as: :destroy_user_session
    
    get    "signup"  => "users/registrations#new",    as: :new_user_registration
    post   "signup"  => "users/registrations#create", as: :user_registration
    put    "signup"  => "users/registrations#update", as: :update_user_registration
    get    "account" => "users/registrations#edit",   as: :edit_user_registration
  end

end

app/models/getaway_search.rb
class GetawaySearch < ActiveRecord::Base

  ORIGINS = ["ATL", "ORD", "DEN", "LAX", "MIA", "LAS", "DFW", "CLT", "JFK", "IND", "SEA"]
  DESTINATIONS = ["ATL","DEN","SFO","LAX","SEA","MIA","MSY", "LAS"]
  AIRPORT_NAMES =  {"ATL" => "Atlanta", "ORD" => "Chicago O'Hare", "DEN" => "Denver", "LAX" => "Los Angeles", "MIA" => "Miami", "LAS" => "Las Vegas", "DFW" => "Dallas/Fort Worth", "CLT" => "Charlotte", "JFK" => "New York JFK", "IND" => "Indianapolis", "SEA" => "Seattle", "SFO" => "San Francisco", "MSY" => "New Orleans"}

  VALID_LEAVE_ON_VALUES = { a_friday: "A Friday", a_thursday: "A Thursday" }
  VALID_RETURN_ON_VALUES = { following_sunday: "The following Sunday", following_monday: "The following Monday" }

  belongs_to :user
  has_many :trip_options, :dependent => :destroy
  has_many :api_results, :dependent => :destroy

  validates_presence_of :fly_from, :price_limit#, :leave_on, :return_on
  # validates_inclusion_of :leave_on, :in => VALID_LEAVE_ON_VALUES.keys.map(&:to_s)
  # validates_inclusion_of :return_on, :in => VALID_RETURN_ON_VALUES.keys.map(&:to_s)
  # validates_formatting_of :ip_address, using: :ip_address_v4


  acts_as_votable

  def get_api_result(param_options={})

    fly_to = param_options[:fly_to]
    fly_from = param_options[:fly_from]

    raise "Search is not valid!" unless self.valid? && fly_from.present? && fly_to.present? && DESTINATIONS.include?(fly_to) && fly_from != fly_to

    key = "#{fly_from}_to_#{fly_to}_on_#{param_options[:departure_date].strftime("%m_%d_%Y")}_return_#{param_options[:return_date].strftime("%m_%d_%Y")}"
    begin
      response_body = DbCacheItem.get(key, valid_for: 1.day) do
        request = GoogleFlightsRequest.new(
          :max_price => "1000.00",#'%.02f' % param_options[:price_limit],
          :departure_airport => fly_from,
          :destination_airport => fly_to,
          :departure_date => param_options[:departure_date],#DateTime.now + 5.weeks,
          :return_date => param_options[:return_date]#DateTime.now + 5.weeks + 3.days
        )
        response = request.make_request!
        response.body
      end
    rescue Exception
      response_body = nil
    end

    if response_body.present?
      api_res = ApiResult.new(result_json: JSON.parse(response_body),
                  fly_from: fly_from,
                  fly_to: fly_to
                )
      self.api_results << api_res
    end
  end

  def add_trip_options!
    real_price_limit = price_limit + 10.0
    api_results.each do |res|
      adapter = GoogleFlightsAdapter.new(res)
      adapter.trip_options.each do |trip_option|
        if trip_option.price <= real_price_limit
          self.trip_options << trip_option
        else
          trip_option.destroy
        end

      end
    end
  end

  def earliest_departure_date
    Chronic.parse("next #{leave_on.gsub('a_', '')}")
  end

  def cheapest_trip_option
    trip_options.sort_by(&:price).first
  end

  def perform_search!


    [
      # earliest_departure_date,
      earliest_departure_date + 7.days#,
      # earliest_departure_date + 14.days
      # earliest_departure_date + 21.days  # TODO: move into worker to do longer searches
    ].each do |possible_departure_date|
      (DESTINATIONS - [fly_from]).each do |destination|
        get_api_result(
          price_limit: price_limit,
          fly_from: fly_from,
          fly_to: destination,
          departure_date: possible_departure_date,
          return_date: possible_departure_date + 2.days
        )
      end
    end

    add_trip_options!
  end

  private ############################################################################################################################



  def get_first_departure_date
    Chronic.parse("next #{leave_on.gsub('a_', '')}") + 7.hours
  end

end

app/controllers/getaway_searches_controller.rb
class GetawaySearchesController < ApplicationController

  #->Prelang (scaffolding:rails/scope_to_user)
  before_filter :require_user_signed_in, only: [:edit, :update, :vote, :destroy]

  before_action :set_getaway_search, only: [:show, :edit, :update, :destroy, :render_trip_options_list, :vote]

  # GET /getaway_searches
  # GET /getaway_searches.json
  def index
    @getaway_searches = GetawaySearch.all.order("created_at desc")
    @getaway_search = GetawaySearch.new(leave_on: "a_friday", return_on: "following_sunday")
  end

  # GET /getaway_searches/1
  # GET /getaway_searches/1.json
  def show
  end

  # GET /getaway_searches/new
  def new
    @getaway_search = GetawaySearch.new(leave_on: "a_friday", return_on: "following_sunday")
    # @getaway_searches = GetawaySearch.all
  end

  # GET /getaway_searches/1/edit
  def edit
  end

  # POST /getaway_searches
  # POST /getaway_searches.json
  def create
    @getaway_search = GetawaySearch.new(getaway_search_params)
    @getaway_search.user = current_user
    @getaway_search.leave_on = "a_friday"
    @getaway_search.return_on = "following_sunday"

    respond_to do |format|
      if @getaway_search.save
        Resque.enqueue(GetawaySearchWorker, @getaway_search.id)
        format.html { redirect_to @getaway_search, notice: 'Getaway search was successfully created.' }
        format.json { render :show, status: :created, location: @getaway_search }
      else
        format.html { render :new }
        format.json { render json: @getaway_search.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /getaway_searches/1
  # PATCH/PUT /getaway_searches/1.json
  def update
    respond_to do |format|
      if @getaway_search.update(getaway_search_params)
        format.html { redirect_to @getaway_search, notice: 'Getaway search was successfully updated.' }
        format.json { render :show, status: :ok, location: @getaway_search }
      else
        format.html { render :edit }
        format.json { render json: @getaway_search.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /getaway_searches/1
  # DELETE /getaway_searches/1.json
  def destroy
    @getaway_search.destroy
    respond_to do |format|
      format.html { redirect_to getaway_searches_url, notice: 'Getaway search was successfully destroyed.' }
      format.json { head :no_content }
    end
  end


  #->Prelang (voting/acts_as_votable)
  def vote

    direction = params[:direction]

    # Make sure we've specified a direction
    raise "No direction parameter specified to #vote action." unless direction

    # Make sure the direction is valid
    unless ["like", "bad"].member? direction
      raise "Direction '#{direction}' is not a valid direction for vote method."
    end

    @getaway_search.vote_by voter: current_user, vote: direction

    redirect_to action: :index
  end

  #TODO: hamlbars or something...yes I'm lazy in my side projects!
  def render_trip_options_list
    render partial: "trip_options/list", locals: { trip_options: @getaway_search.trip_options.sort_by(&:price) }
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_getaway_search
      @getaway_search = GetawaySearch.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def getaway_search_params
      params.require(:getaway_search).permit(:fly_from, :price_limit, :user_id, :ip_address, :leave_on, :return_on)
    end
end

app/helpers/getaway_searches_helper.rb
module GetawaySearchesHelper
end

app/views/getaway_searches/_form.html.erb
<%= form_for @getaway_search, :html => { :class => 'form-horizontal form-model' } do |f| %>
  <div class="form-group">
    <%= f.label :price_limit, :class => 'control-label col-md-2' %>
    <div class="col-md-10">
      <%= f.text_field :price_limit, :class => 'text-field form-control' %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :ip_address, :class => 'control-label col-md-2' %>
    <div class="col-md-10">
      <%= f.text_field :ip_address, :class => 'text-field form-control' %>
    </div>
  </div>

  <div class="form-group">
    <div class='col-md-offset-2 col-md-10'>
      <%= f.submit nil, :class => 'btn btn-primary' %>
      <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
                  getaway_searches_path, :class => 'btn btn-default' %>
    </div>
  </div>
<% end %>

app/views/getaway_searches/_form.html.haml
= semantic_form_for @getaway_search, :html => { :class => 'form-horizontal form-model' } do |f|
  .form-group
    = f.label :fly_from, :class => 'control-label col-md-2'
    .col-md-10
      - fly_from_options = GetawaySearch::ORIGINS.map{ |origin| [GetawaySearch::AIRPORT_NAMES[origin], origin] }.sort_by(&:first)
      =# f.text_field :fly_from, :class => 'text-field form-control'
      = f.input :fly_from, :as => :select, :collection => fly_from_options, :class => 'text-field form-control', label: false, include_blank: false
  .form-group
    = f.label :price_limit, :class => 'control-label col-md-2'
    .col-md-10
      - select_options = [100, 200, 300, 500, 700, 1000].map{ |opt| [money_format(opt), opt] }
      = f.input :price_limit, :as => :select, :collection => select_options, :class => 'text-field form-control', label: false, include_blank: false
  .form-group
    .col-md-offset-2.col-md-10
      = f.submit "Find a weekend getaway!", :class => 'btn btn-primary'
      - unless local_assigns[:hide_cancel]
        = link_to t('.cancel', :default => t("helpers.links.cancel")), getaway_searches_path, :class => 'btn btn-default'

app/views/getaway_searches/_list.html.haml
- model_class = GetawaySearch
- local_assigns[:getaway_searches] ||= []
-#%table.table.table-striped
%table.table.table-striped.table-hover.form-model
  %thead
    %tr
      %th Fly From
      %th= model_class.human_attribute_name(:price_limit)
      %th= "Cheapest Option"
      %th=# t '.actions', :default => t("helpers.actions")
  %tbody
    - local_assigns[:getaway_searches].each do |getaway_search|
      %tr
        %td.lead= getaway_search.fly_from
        %td.lead= money_format(getaway_search.price_limit)
        - cheapest_option = getaway_search.cheapest_trip_option
        - if cheapest_option.present?
          %td{ style: "max-width: 525px;" }
            = render partial: "trip_options/summary_info_cell.html.haml", locals: { trip_option: cheapest_option }
        - else
          %td
        %td
          = link_to("Show Trip Options", getaway_search_path(getaway_search), :class => "btn btn-primary")
          =# link_to getaway_search_path(getaway_search), :class => 'btn btn-xs', :title => "#{ t('.show', :default => t('helpers.links.show')) }" do
          =# glyph 'info-sign'
          =# glyph 'pencil'
          =# link_to getaway_search_path(getaway_search), :method => :delete, :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) }, :class => 'btn btn-xs', :title => "#{ t('.destroy', :default => t('helpers.links.destroy')) }" do
          =# glyph 'remove'

app/views/getaway_searches/edit.html.erb
<%- model_class = GetawaySearch -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => GetawaySearch %></h1>
</div>
<%= render :partial => 'form' %>

app/views/getaway_searches/index.html.haml
= render :partial => 'form', locals: { hide_cancel: true }
%h2 Recent Searches
= render partial: "list", locals: { getaway_searches: @getaway_searches }

app/views/getaway_searches/new.html.haml
= render :partial => 'form'

app/views/getaway_searches/show.html.haml
- model_class = GetawaySearch
.page-header
  %h1= t '.title', :default => GetawaySearch

.lead
  = "Fly From: #{@getaway_search.fly_from}"
.lead
  = "Price Limit: #{money_format(@getaway_search.price_limit)}"
.form-group
  = link_to t('.back', :default => t("helpers.links.back")), |
    getaway_searches_path, :class => 'btn btn-default'       |
  -#
  = link_to t('.edit', :default => t("helpers.links.edit")),               |
    edit_getaway_search_path(@getaway_search), :class => 'btn btn-default' |
  -#
  = link_to t('.destroy', :default => t("helpers.links.destroy")),                                               |
    getaway_search_path(@getaway_search),                                                                        |
    :method => 'delete',                                                                                         |
    :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) }, |
    :class => 'btn btn-danger'                                                                                   |

.trip-options
  - if @getaway_search.search_complete?
    %h2 Loading Results....
  - else
    %h2 Search in Progress!  Results will show here when search is complete.


:javascript
  var refreshIntervalId
  $(document).ready(function(){
    refreshIntervalId = setInterval(doAjaxCall, 3000);
  });

  function doAjaxCall(){
    var result = false;
    $.ajax({
      url: "#{@getaway_search.id}.json"
    }).done(function(json){
      if (json["search_complete"]) {
        clearInterval(refreshIntervalId);
        getTripOptionsListHtml();
      }
    });
  }

  function getTripOptionsListHtml(){
    $.ajax({
      url: "#{@getaway_search.id}/render_trip_options_list"
    }).done(function(html){
      $(".trip-options").html(html);
    });
  }